<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-09T16:41:57 IST" name="Default suite" finished-at="2022-08-09T16:43:53 IST" duration-ms="115928">
    <groups>
    </groups>
    <test started-at="2022-08-09T16:41:57 IST" name="Default test" finished-at="2022-08-09T16:43:53 IST" duration-ms="115928">
      <class name="page.Driven">
        <test-method is-config="true" signature="setup()[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:41:58 IST" name="setup" finished-at="2022-08-09T16:42:28 IST" duration-ms="30429" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:42:28 IST" name="loginTest" data-provider="Credentials1" finished-at="2022-08-09T16:42:34 IST" duration-ms="5823" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sugan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sugan]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials> but was:<https://opensource-demo.orangehrmlive.com/index.php/dashboard>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials> but was:<https://opensource-demo.orangehrmlive.com/index.php/dashboard>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at page.Driven.loginTest(Driven.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:42:34 IST" name="tearDown" finished-at="2022-08-09T16:42:35 IST" duration-ms="1248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:42:35 IST" name="setup" finished-at="2022-08-09T16:43:08 IST" duration-ms="32416" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:43:08 IST" name="loginTest" data-provider="Credentials1" finished-at="2022-08-09T16:43:13 IST" duration-ms="5077" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sibi]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sibi]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials> but was:<https://opensource-demo.orangehrmlive.com/index.php/dashboard>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials> but was:<https://opensource-demo.orangehrmlive.com/index.php/dashboard>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at page.Driven.loginTest(Driven.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:43:13 IST" name="tearDown" finished-at="2022-08-09T16:43:15 IST" duration-ms="2398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:43:15 IST" name="setup" finished-at="2022-08-09T16:43:36 IST" duration-ms="21290" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:43:36 IST" name="loginTest" data-provider="Credentials1" finished-at="2022-08-09T16:43:52 IST" duration-ms="15545" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:page.Driven@2c3dec30]" started-at="2022-08-09T16:43:52 IST" name="tearDown" finished-at="2022-08-09T16:43:53 IST" duration-ms="1227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- page.Driven -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
